// Generated by CoffeeScript 1.8.0
(function() {
  var Htmlparser, MKTS, P1, RMY, TEXT, TRM, TYPES, XNCHR, alert, app, badge, cell_idx, chrs, debug, doc, echo, express, help, info, njs_fs, njs_path, rpr, server, urge, verbose, warn, whisper,
    __modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

  njs_path = require('path');

  njs_fs = require('fs');

  TEXT = require('coffeenode-text');

  TYPES = require('coffeenode-types');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'TYPESETTER';

  info = TRM.get_logger('info', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  urge = TRM.get_logger('urge', badge);

  whisper = TRM.get_logger('whisper', badge);

  help = TRM.get_logger('help', badge);

  echo = TRM.echo.bind(TRM);

  RMY = require('remarkably');

  Htmlparser = (require('htmlparser2')).Parser;

  XNCHR = require('/Volumes/Storage/cnd/node_modules/jizura-datasources/src/XNCHR.coffee');

  P1 = require('pipedreams');

  verbose = true;

  verbose = false;

  this.new_document = function(settings) {
    var R;
    R = {
      keep_x_grid: false,
      cells: [],
      cells_per_line: 8,
      lines_per_page: 6,
      idx: 0,
      size: 1
    };
    return R;
  };

  this._set = function(me, pos, content) {
    var idx, size, xy;
    idx = this.idx_from_pos(me, pos);
    xy = this.xy_from_pos(me, pos);
    size = me.size;
    this._validate_xy(me, xy, size);
    me['cells'][idx] = content;
    return me;
  };

  this.put = function(me, content) {
    var idx;
    idx = me.idx;
    this._set(me, idx, content);
    return this.advance_chr(me);
  };

  this.advance_chr = function(me) {
    debug('### TAINT advance_chr simplified ###');
    me['idx'] += 1;
    return me;
  };


  /*
   *===========================================================================================================
  
  
  
   .d8888b.   .d88888b.   .d88888b.  8888888b.  8888888b.  8888888 888b    888        d8888 88888888888 8888888888  .d8888b.
  d88P  Y88b d88P" "Y88b d88P" "Y88b 888   Y88b 888  "Y88b   888   8888b   888       d88888     888     888        d88P  Y88b
  888    888 888     888 888     888 888    888 888    888   888   88888b  888      d88P888     888     888        Y88b.
  888        888     888 888     888 888   d88P 888    888   888   888Y88b 888     d88P 888     888     8888888     "Y888b.
  888        888     888 888     888 8888888P"  888    888   888   888 Y88b888    d88P  888     888     888            "Y88b.
  888    888 888     888 888     888 888 T88b   888    888   888   888  Y88888   d88P   888     888     888              "888
  Y88b  d88P Y88b. .d88P Y88b. .d88P 888  T88b  888  .d88P   888   888   Y8888  d8888888888     888     888        Y88b  d88P
   "Y8888P"   "Y88888P"   "Y88888P"  888   T88b 8888888P"  8888888 888    Y888 d88P     888     888     8888888888  "Y8888P"
  
  
  
   *===========================================================================================================
   */

  this.idx_from_xy = function(me, xy, allow_wrap) {
    var cells_per_line, lines_per_page, x, y;
    if (allow_wrap == null) {
      allow_wrap = false;
    }
    if (allow_wrap) {
      throw new Error("wrapping not implemented");
    }
    cells_per_line = me.cells_per_line, lines_per_page = me.lines_per_page;
    x = xy[0], y = xy[1];
    if (!(x < cells_per_line)) {
      throw Error("illegal x " + (rpr(x)));
    }
    return y * cells_per_line + x;
  };

  this.xy_from_idx = function(me, idx) {
    var cells_per_line, lines_per_page;
    cells_per_line = me.cells_per_line, lines_per_page = me.lines_per_page;
    return [__modulo(idx, cells_per_line), Math.floor(idx / cells_per_line)];
  };

  this.idx_from_pos = function(me, pos) {
    if (TYPES.isa_number(pos)) {
      return pos;
    }
    return this.idx_from_xy(me, pos);
  };

  this.xy_from_pos = function(me, pos) {
    if (TYPES.isa_list(pos)) {
      return pos;
    }
    return this.xy_from_idx(me, pos);
  };

  this._validate_xy = function(me, xy, size) {
    var keep_x_grid, old_content, x, y;
    keep_x_grid = me.keep_x_grid;
    x = xy[0], y = xy[1];
    if (keep_x_grid && size > 1) {
      if (x % size !== 0) {
        throw new Error("" + (this._rpr_xy(xy)) + " not within x grid size " + size);
      }
    }
    if (y % size !== 0) {
      throw new Error("" + (this._rpr_xy(xy)) + " not within y grid size " + size);
    }
    old_content = me['cells'][this.idx_from_xy(me, xy)];
    if (old_content !== void 0) {
      throw new Error("cannot overwrite " + (rpr(old_content)) + " with " + (rpr(content)) + " " + (this._rpr_xy(xy)));
    }
    return me;
  };

  this._rpr_pos = function(pos) {
    if (TYPES.isa_number(pos)) {
      return this._rpr_idx(pos);
    } else {
      return this._rpr_xy(pos);
    }
  };

  this._rpr_xy = function(xy) {
    return "@(" + xy[0] + ", " + xy[0] + ")";
  };

  this._rpr_idx = function(idx) {
    return this._rpr_xy(this.xy_from_pos(idx));
  };


  /*
   *===========================================================================================================
  
  
  
  888    888 8888888888 888      8888888b.  8888888888 8888888b.   .d8888b.
  888    888 888        888      888   Y88b 888        888   Y88b d88P  Y88b
  888    888 888        888      888    888 888        888    888 Y88b.
  8888888888 8888888    888      888   d88P 8888888    888   d88P  "Y888b.
  888    888 888        888      8888888P"  888        8888888P"      "Y88b.
  888    888 888        888      888        888        888 T88b         "888
  888    888 888        888      888        888        888  T88b  Y88b  d88P
  888    888 8888888888 88888888 888        8888888888 888   T88b  "Y8888P"
  
  
  
   *===========================================================================================================
   */

  this._is_even = function(n) {
    return n / 2 === Math.floor(n / 2);
  };

  this._next_odd_int = function(n) {
    return ((Math.floor(n / 2)) * 2) + 1;
  };

  this.get_cell_count_to_row_end = function(me, pos) {
    var x, y, _ref;
    _ref = this.xy_from_pos(me, pos), x = _ref[0], y = _ref[1];
    return me['cells_per_line'] - (__modulo(x, me['cells_per_line']));
  };

  if (module.parent == null) {
    MKTS = this;
    doc = MKTS.new_document();
    cell_idx = 0;
    chrs = XNCHR.chrs_from_text('畢昇發明活字印刷術宋沈括著《夢溪筆談》卷十八記載');
    express = require('express');
    app = express();
    app.get("/", function(request, response) {
      var cell, idx, last_y, me, x, y, _i, _len, _ref, _ref1;
      me = doc;
      last_y = null;
      MKTS.put(me, chrs[cell_idx]);
      cell_idx += 1;
      response.write("<table border=1>\n");
      _ref = me['cells'];
      for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
        cell = _ref[idx];
        _ref1 = MKTS.xy_from_idx(me, idx), x = _ref1[0], y = _ref1[1];
        if (y !== last_y) {
          if (y !== 0) {
            response.write("</tr>\n");
          }
          response.write("<tr>");
          last_y = y;
        }
        response.write("<td>" + cell + "</td>");
      }
      response.write("</tr></table>\n");
      return response.end();
    });
    server = app.listen(3000, function() {
      var host, port;
      host = server.address().address;
      port = server.address().port;
      return help("Example app listening at http://" + host + ":" + port);
    });
  }

}).call(this);
