// Generated by CoffeeScript 1.8.0
(function() {
  var Htmlparser, P1, RMY, TEXT, TRM, TYPES, XNCHR, alert, badge, debug, echo, help, info, njs_fs, njs_path, rpr, urge, verbose, warn, whisper,
    __modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

  njs_path = require('path');

  njs_fs = require('fs');

  TEXT = require('coffeenode-text');

  TYPES = require('coffeenode-types');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'TYPESETTER';

  info = TRM.get_logger('info', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  urge = TRM.get_logger('urge', badge);

  whisper = TRM.get_logger('whisper', badge);

  help = TRM.get_logger('help', badge);

  echo = TRM.echo.bind(TRM);

  RMY = require('remarkably');

  Htmlparser = (require('htmlparser2')).Parser;

  XNCHR = require('XNCHR.coffee');

  P1 = require('pipedreams');

  verbose = true;

  verbose = false;

  this.new_document = function(settings) {
    var R;
    R = {
      keep_x_grid: false,
      cells: [],
      cells_per_line: 8,
      lines_per_page: 6,
      idx: 0,
      size: 1
    };
    return R;
  };

  this._get = function(me, pos, fallback) {
    var R, idx;
    idx = this.idx_from_pos(me, pos);
    R = me['cells'][idx];
    if (R === void 0) {
      if (arguments.length > 2) {
        return fallback;
      }
      throw new Error("position " + (this._rpr_pos(me, pos)) + " out of bounds");
    }
    return R;
  };

  this._set = function(me, pos, content) {
    var idx, size, xy;
    idx = this.idx_from_pos(me, pos);
    xy = this.xy_from_pos(me, pos);
    size = me.size;
    this._validate_xy(me, xy, size);
    me['cells'][idx] = content;
    return me;
  };

  this.put = function(me, content) {
    var idx;
    idx = me.idx;
    this._set(me, idx, content);
    return this.advance_chr(me);
  };

  this.advance_chr = function(me) {
    debug('### TAINT advance_chr simplified ###');
    me['idx'] += 1;
    return me;
  };


  /*
   *===========================================================================================================
  
  
  
   .d8888b.   .d88888b.  888b     d888 8888888b.  8888888b.  8888888888  .d8888b.   .d8888b.
  d88P  Y88b d88P" "Y88b 8888b   d8888 888   Y88b 888   Y88b 888        d88P  Y88b d88P  Y88b
  888    888 888     888 88888b.d88888 888    888 888    888 888        Y88b.      Y88b.
  888        888     888 888Y88888P888 888   d88P 888   d88P 8888888     "Y888b.    "Y888b.
  888        888     888 888 Y888P 888 8888888P"  8888888P"  888            "Y88b.     "Y88b.
  888    888 888     888 888  Y8P  888 888        888 T88b   888              "888       "888
  Y88b  d88P Y88b. .d88P 888   "   888 888        888  T88b  888        Y88b  d88P Y88b  d88P
   "Y8888P"   "Y88888P"  888       888 888        888   T88b 8888888888  "Y8888P"   "Y8888P"
  
  
   *===========================================================================================================
   */

  this.set_size = function(me, size) {
    if (size !== 1 && size !== 2 && size !== 3 && size !== 4) {
      throw new Error("unsupported size " + (rpr(size)));
    }
    me['size'] = size;
    return me;
  };

  this.compress = function(me) {
    var idx, size, y, y0, y1, _, _ref;
    size = me.size, idx = me.idx;
    if (!(size > 1)) {
      throw new Error("unsupported size " + (rpr(size)) + " for compress");
    }
    _ref = this.xy_from_idx(me, idx), _ = _ref[0], y = _ref[1];
    y0 = this._previous_grid_int(y, size);
    y1 = this._next_grid_int(y, size);
    debug("compressing lines " + y0 + " .. " + y1);
    return me;
  };


  /*
   *===========================================================================================================
  
  
  
   .d8888b.   .d88888b.   .d88888b.  8888888b.  8888888b.  8888888 888b    888        d8888 88888888888 8888888888  .d8888b.
  d88P  Y88b d88P" "Y88b d88P" "Y88b 888   Y88b 888  "Y88b   888   8888b   888       d88888     888     888        d88P  Y88b
  888    888 888     888 888     888 888    888 888    888   888   88888b  888      d88P888     888     888        Y88b.
  888        888     888 888     888 888   d88P 888    888   888   888Y88b 888     d88P 888     888     8888888     "Y888b.
  888        888     888 888     888 8888888P"  888    888   888   888 Y88b888    d88P  888     888     888            "Y88b.
  888    888 888     888 888     888 888 T88b   888    888   888   888  Y88888   d88P   888     888     888              "888
  Y88b  d88P Y88b. .d88P Y88b. .d88P 888  T88b  888  .d88P   888   888   Y8888  d8888888888     888     888        Y88b  d88P
   "Y8888P"   "Y88888P"   "Y88888P"  888   T88b 8888888P"  8888888 888    Y888 d88P     888     888     8888888888  "Y8888P"
  
  
  
   *===========================================================================================================
   */

  this.idx_from_xy = function(me, xy, allow_wrap) {
    var cells_per_line, lines_per_page, x, y;
    if (allow_wrap == null) {
      allow_wrap = false;
    }
    if (allow_wrap) {
      throw new Error("wrapping not implemented");
    }
    cells_per_line = me.cells_per_line, lines_per_page = me.lines_per_page;
    x = xy[0], y = xy[1];
    if (!(x < cells_per_line)) {
      throw Error("illegal x " + (rpr(x)));
    }
    return y * cells_per_line + x;
  };

  this.xy_from_idx = function(me, idx) {
    var cells_per_line, lines_per_page;
    cells_per_line = me.cells_per_line, lines_per_page = me.lines_per_page;
    return [__modulo(idx, cells_per_line), Math.floor(idx / cells_per_line)];
  };

  this.idx_from_pos = function(me, pos) {
    if (TYPES.isa_number(pos)) {
      return pos;
    }
    return this.idx_from_xy(me, pos);
  };

  this.xy_from_pos = function(me, pos) {
    if (TYPES.isa_list(pos)) {
      return pos;
    }
    return this.xy_from_idx(me, pos);
  };

  this.get_last_idx = function(me) {
    return me['cells'].length - 1;
  };

  this.get_last_xy = function(me, pos) {
    return this.xy_from_idx(me, this.get_last_idx(me));
  };

  this._validate_xy = function(me, xy, size) {
    var keep_x_grid, old_content, x, y;
    keep_x_grid = me.keep_x_grid;
    x = xy[0], y = xy[1];
    if (keep_x_grid && size > 1) {
      if (__modulo(x, size) !== 0) {
        throw new Error("" + (this._rpr_xy(me, xy)) + " not within x grid size " + size);
      }
    }
    if (__modulo(y, size) !== 0) {
      throw new Error("" + (this._rpr_xy(me, xy)) + " not within y grid size " + size);
    }
    old_content = me['cells'][this.idx_from_xy(me, xy)];
    if (old_content !== void 0) {
      throw new Error("cannot overwrite " + (rpr(old_content)) + " with " + (rpr(content)) + " " + (this._rpr_xy(me, xy)));
    }
    return me;
  };

  this._rpr_pos = function(me, pos) {
    if (TYPES.isa_number(pos)) {
      return this._rpr_idx(me, pos);
    } else {
      return this._rpr_xy(me, pos);
    }
  };

  this._rpr_xy = function(me, xy) {
    return "@( " + xy[0] + ", " + xy[0] + " )";
  };

  this._rpr_idx = function(me, idx) {
    return this._rpr_xy(me, this.xy_from_pos(idx));
  };


  /*
   *===========================================================================================================
  
  
  
  888    888 8888888888 888      8888888b.  8888888888 8888888b.   .d8888b.
  888    888 888        888      888   Y88b 888        888   Y88b d88P  Y88b
  888    888 888        888      888    888 888        888    888 Y88b.
  8888888888 8888888    888      888   d88P 8888888    888   d88P  "Y888b.
  888    888 888        888      8888888P"  888        8888888P"      "Y88b.
  888    888 888        888      888        888        888 T88b         "888
  888    888 888        888      888        888        888  T88b  Y88b  d88P
  888    888 8888888888 88888888 888        8888888888 888   T88b  "Y8888P"
  
  
  
   *===========================================================================================================
   */

  this._previous_grid_int = function(me, n, module) {
    return (Math.floor(n / module)) * module;
  };

  this._next_grid_int = function(me, n, module) {
    return (this._previous_grid_int(n, module)) + module;
  };


  /*
   *===========================================================================================================
  
  
  
   .d8888b.  8888888888 8888888b.  888     888 8888888888 8888888b.
  d88P  Y88b 888        888   Y88b 888     888 888        888   Y88b
  Y88b.      888        888    888 888     888 888        888    888
   "Y888b.   8888888    888   d88P Y88b   d88P 8888888    888   d88P
      "Y88b. 888        8888888P"   Y88b d88P  888        8888888P"
        "888 888        888 T88b     Y88o88P   888        888 T88b
  Y88b  d88P 888        888  T88b     Y888P    888        888  T88b
   "Y8888P"  8888888888 888   T88b     Y8P     8888888888 888   T88b
  
  
  
   *===========================================================================================================
   */

  this._rpr_cell = function(cell) {
    if (cell === void 0) {
      return '\u3000';
    }
    if (cell === null) {
      return '〼';
    }
    if (TYPES.isa_text(cell)) {
      return cell;
    }
    return rpr(cell);
  };

  this.serve = function() {
    var app, express, me, server;
    express = require('express');
    me = this.new_document();
    app = express();
    app.get("/", (function(_this) {
      return function() {
        var chr_idx, chrs, last_chr_idx;
        chrs = XNCHR.chrs_from_text('畢昇發明活字印刷術宋沈括著《夢溪筆談》卷十八記載');
        chr_idx = 0;
        last_chr_idx = chrs.length - 1;
        return function(request, response) {
          var cell, x, x1, y, y1, _i, _j, _ref, _ref1;
          _this.put(me, chr_idx <= last_chr_idx ? chrs[chr_idx] : '〓');
          chr_idx += 1;
          _ref = _this.get_last_xy(me), x1 = _ref[0], y1 = _ref[1];
          response.write("<table border=1>\n");
          for (y = _i = 0; 0 <= y1 ? _i <= y1 : _i >= y1; y = 0 <= y1 ? ++_i : --_i) {
            response.write("<tr>");
            for (x = _j = 0, _ref1 = me['cells_per_line']; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; x = 0 <= _ref1 ? ++_j : --_j) {
              cell = _this._rpr_cell(_this._get(me, [x, y], void 0));
              response.write("<td>" + cell + "</td>");
            }
            response.write("</tr>\n");
          }
          response.write("</table>\n");
          return response.end();
        };
      };
    })(this)());
    return server = app.listen(3000, function() {
      var host, port;
      host = server.address().address;
      port = server.address().port;
      return help("明快排字机 listening at http://" + host + ":" + port);
    });
  };

  this.get_cell_count_to_row_end = function(me, pos) {
    var x, y, _ref;
    _ref = this.xy_from_pos(me, pos), x = _ref[0], y = _ref[1];
    return me['cells_per_line'] - (__modulo(x, me['cells_per_line']));
  };

  if (module.parent == null) {
    this.serve();
  }

}).call(this);
