// Generated by CoffeeScript 1.8.0
(function() {
  var BITSNPIECES, TEACUP, TRM, alert, badge, debug, help, info, log, name_, rpr, urge, warn, whisper;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = '明快排字机/server';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  urge = TRM.get_logger('urge', badge);

  BITSNPIECES = require('coffeenode-bitsnpieces');

  TEACUP = require('coffeenode-teacup');

  for (name_ in TEACUP) {
    eval("" + name_ + " = TEACUP[ " + (rpr(name_)) + " ]");
  }

  this.main = function(request, response) {
    return render((function(_this) {
      return function() {
        DOCTYPE(5);
        return HTML(function() {
          HEAD(function() {
            COMMENT('#head-top');
            META({
              charset: 'utf-8'
            });
            TITLE('明快排字机');
            COFFEESCRIPT(function() {
              var after, notification_options, notify;
              after = function(seconds, method) {
                return setTimeout(method, seconds * 1000);
              };
              notification_options = {
                sticky: false,
                click: function(event, notification) {
                  return notification.close();
                }
              };
              notify = function(title, text) {
                var message;
                message = {
                  title: title,
                  text: text
                };
                return ($('#notify-wrap')).notify('create', 'notify-default', message, notification_options);
              };
              return ($('document')).ready(function() {
                var flash_messages, idx, text, title, _i, _ref, _ref1;
                ($('#notify-wrap')).notify({
                  speed: 250,
                  expires: 5000
                });
                if ((flash_messages = $.cookie('flash-messages')) != null) {
                  flash_messages = JSON.parse(flash_messages);
                  for (idx = _i = _ref = flash_messages.length - 1; _i >= 0; idx = _i += -1) {
                    _ref1 = flash_messages[idx], title = _ref1[0], text = _ref1[1];
                    notify(title, text);
                  }
                  flash_messages.length = 0;
                  return $.cookie('flash-messages', '[]');
                }
              });
            });
            LINK({
              rel: 'shortcut icon',
              href: '/public/favicon.ico?v6'
            });
            return COMMENT('#head-bottom');
          });
          return BODY(function() {
            COMMENT('#body-top');
            return COMMENT('#body-bottom');
          });
        });
      };
    })(this));
  };

}).call(this);
